urls.py
from django.urls import path 

from  purchase_request import views

app_name = "purchase_request"





urlpatterns = [
	path('lista/purchase/request', views.listapurchaserequest, name='listapurchaserequest'),
	path('request/purchase', views.requestpurchase, name='requestpurchase'),
	path('edit/request/purchase/<str:id>/', views.editrequestpurchase, name='editrequestpurchase'),
	path('detallu/purchase/request/<str:id>/', views.detallupurchaserequest, name='detallupurchaserequest'),
	path('add/item/purchase/<str:id_riquest>/', views.additempurchase, name='additempurchase'),

	path('edit/item/purchase/<str:id_item>/', views.edititempurchase, name='edititempurchase'),
	path('apaga/item/purchase/<str:id_item>/', views.apagaitempurchase, name='apagaitempurchase'),
	path('aproved/item/purchase/<str:id_item>/', views.aproveditempurchase, name='aproveditempurchase'),
	path('riject/item/purchase/<str:id_item>/', views.rijectitempurchase, name='rijectitempurchase'),
	path('deliver/item/purchase/<str:id_item>/', views.deliveritempurchase, name='deliveritempurchase'),
	path('send/purchase/request/<str:id>/', views.sendpurchaserequest, name='sendpurchaserequest'),


	path('acepted/purchase/request/<str:id>/', views.aceptedpurchaserequest, name='aceptedpurchaserequest'),
	path('rijected/purchase/request<str:id>/', views.rijectedpurchaserequest, name='rijectedpurchaserequest'),

															 
																 
		

]

templates/purchase_request/detallu_purchaserequest.html
{% extends 'utilizador/layout.html' %}
{% block content %}

{% load crispy_forms_tags %}

{% load fegt9_mpg_proteksaun_url %}


		<!-- ============================================================== -->
						<!-- pageheader  -->
						<!-- ============================================================== -->
						<div class="row">
							<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
								<div class="page-header">
									<h2 class="pageheader-title">Detallu husi Purchase request  </h2>
									<p class="pageheader-text">Nulla euismod urna eros, sit amet scelerisque torton lectus vel mauris facilisis faucibus at enim quis massa lobortis rutrum.</p>
									<div class="page-breadcrumb">
										<nav aria-label="breadcrumb">
											<ol class="breadcrumb">
												<li class="breadcrumb-item"><a href="#" class="breadcrumb-link">CVTL</a></li>
												<li class="breadcrumb-item active" aria-current="page">Hris Painel</li>
											</ol>

                                            
										</nav>
									</div>
								</div>
							</div>
						</div>
						<!-- ============================================================== -->
						<!-- end pageheader  -->
						<!-- ============================================================== -->
						<div class="ecommerce-widget">
	
				
                            <div class="row">
                                <div class="  col-lg-12 col-md-12 col-sm-12 col-12">
                                    <div class="card">
                                        <div class="card-header p-4">
                                             <a class="pt-2 d-inline-block" href="index.html">
												<b>Titulu </b> : {{purchaserequest.title}} <br>
												<b>Atividade :</b> {{purchaserequest.activity}} <br> <b>Project :</b> {{purchaserequest.project}} </a>
                                           
                                            <div class="float-right"> <h3 class="mb-0">Purchase Request</h3>
												{{purchaserequest.request_date}}</div>
                                        </div>
                                        <div class="card-body">
                                       <legend>
										<h5 class="card-header">Purchase Request  <a href="{% url 'purchase_request:additempurchase'  purchaserequest.id|encrypt_id_tag  %}" class="btn btn-primary btn-sm float-right ">  <i class="far fa-paper-plane"></i> Add Item</a></h5>

                                        
									   </legend>
									   <div class="table-responsive">
										<table class="table table-sm table-bordered">
											<thead class="bg-light">
												<tr class="border-0">
													<th class="border-0">Nu</th>
													<th class="border-0"> Item Description</th>
											
													<th class="border-0">Description</th>
	
													<th class="border-0">Quantity</th>
													<th class="border-0">Unit</th>
													<th class="border-0">Delivery</th>
													<th class="border-0">Status</th>
													<th class="border-0">#</th>
											
												</tr>
											</thead>
											<tbody>
	
												{% for dados in itempurchaserequest %}
												<tr>
												
													<td>{{forloop.counter}}</td>
													<td>{{dados.item_description}}</td>
				
													<td>{{dados.description}}</td>
													<td>{{dados.quantity}}</td>
													<td>{{dados.unit}}</td>
													<td>{{dados.is_delivery}}</td>
													<td>
														
														{% if dados.status == 'Rejected' %}
														<font color='red'>
															{{dados.status}}
														</font>
														{% else %}

														{{dados.status}}
													  	{% endif %}
														
													</td>
							
											
													<td>
	
	
														
			 <a href="{% url 'purchase_request:edititempurchase' dados.id|encrypt_id_tag %}" class="btn btn-primary btn-sm" >  <i class="fas fa-edit"></i> </a>
													  <a href="{% url 'purchase_request:apagaitempurchase' dados.id|encrypt_id_tag %}" class="btn btn-primary btn-sm" >  <i class="fas fa-trash"></i> </a>


													  {% if dados.status == 'Rejected' %}
													  <a href="{% url 'purchase_request:aproveditempurchase' dados.id|encrypt_id_tag %}" class="btn btn-primary btn-sm" >  <i class="fas fa-check"></i> Aproved </a>

													  {% endif %}

													  {% if dados.status == 'Aproved' or dados.status == 'Pendende'  %}
													  	 
													  <a href="{% url 'purchase_request:rijectitempurchase' dados.id|encrypt_id_tag %}" class="btn btn-danger btn-sm" >  <i class="fas fa-window-close"></i> Rijected </a>
												
													  {% endif %}




													  <a href="{% url 'purchase_request:deliveritempurchase' dados.id|encrypt_id_tag %}" class="btn btn-primary btn-sm" >  <i class="fas fa-check"></i> Deliver </a>
												
													
													 
	
													</td>
												</tr>
												{% endfor %}
											
											</tbody>
										</table>


									   </div>
									  
                                        </div>
                                        <div class="card-footer bg-white">
                                            <p class="mb-0">2983 Glenview Drive Corpus Christi, TX 78476</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
						


							<div class="row">
                                <div class="  col-lg-12 col-md-12 col-sm-12 col-12">
                                    <div class="card">
                               
                                        <div class="card-body" style="background-color: #efeff6;">
                              
								

			{% include 'timeline.html' %}
									   </div>
									  
                                        </div>
                                        <div class="card-footer bg-white">
                                            <p class="mb-0">2983 Glenview Drive Corpus Christi, TX 78476</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
						</div>



{% endblock content %}

templates/purchase_request/lista_purchaserequest.html
{% extends 'utilizador/layout.html' %}
{% block content %}
{% load fegt9_mpg_proteksaun_url %}

		<!-- ============================================================== -->
						<!-- pageheader  -->
						<!-- ============================================================== -->
						<div class="row">
							<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
								<div class="page-header">
									<h2 class="pageheader-title">Purchase Request Order </h2>
									<p class="pageheader-text">Nulla euismod urna eros, sit amet scelerisque torton lectus vel mauris facilisis faucibus at enim quis massa lobortis rutrum.</p>
									<div class="page-breadcrumb">
										<nav aria-label="breadcrumb">
											<ol class="breadcrumb">
												<li class="breadcrumb-item"><a href="#" class="breadcrumb-link">CVTL</a></li>
												<li class="breadcrumb-item active" aria-current="page">Hris Painel</li>
											</ol>

                                            
										</nav>
									</div>
								</div>
							</div>
						</div>
						<!-- ============================================================== -->
						<!-- end pageheader  -->
						<!-- ============================================================== -->
						<div class="ecommerce-widget">
	
				
							<div class="row">
								<!-- ============================================================== -->
						  
								<!-- ============================================================== -->
	
											  <!-- recent orders  -->
								<!-- ============================================================== -->
								<div class="col-xl-12 col-lg-12 col-md-6 col-sm-12 col-12">
									<div class="card">
										<h5 class="card-header">Purchase Request  <a href="{% url 'purchase_request:requestpurchase' %}" class="btn btn-primary btn-sm float-right ">  <i class="far fa-paper-plane"></i> Request purchase</a></h5>      
                                        
                                     
										<div class="card-body p-0">
											<div class="table-responsive">
												<table class="table table-sm">
													<thead class="bg-light">
														<tr class="border-0">
															<th class="border-0">Nu</th>
															<th class="border-0">Titulu</th>
															<th class="border-0">Request Date</th>
													
															<th class="border-0">Routine</th>
				
															<th class="border-0">Em parts</th>
														
															<th class="border-0">Is urgent</th>
															<th class="border-0">Status</th>
															<th class="border-0">#</th>
													
														</tr>
													</thead>
													<tbody>

                                                        {% for dados in dadospr %}
														<tr>
														
															<td>{{forloop.counter}}</td>
															<td>{{dados.title}}</td>
															<td>{{dados.request_date}}</td>
														
															<td>{{dados.routine}}</td>
															<td>{{dados.em_parts}}</td>
													
                                                            <td>{{dados.is_urgent}}</td>
															<td>
																{% if dados.is_draft %}
																Draft |     <a href="{% url 'purchase_request:sendpurchaserequest' dados.id|encrypt_id_tag %}" class="btn btn-primary btn-sm" > Send  <i class="far fa-paper-plane"></i>  </a>
                                                       

																{% else %}
																<font color="green">Send</font>
																{% endif %}

															</td>
													
															<td>


                                                                

                                                             <!-- <a href="{% url 'rekrutamentu:publikavaga' dados.id|encrypt_id_tag %}" class="btn btn-primary btn-sm" >  <i class=" fas fa-volume-up"></i> Publika vaga</a> -->
                                                             <a href="{% url 'purchase_request:editrequestpurchase' dados.id|encrypt_id_tag %}" class="btn btn-primary btn-sm" >  <i class="fas fa-edit"></i> </a>
                                                             <!-- <a href="{% url 'rekrutamentu:publikavaga' dados.id|encrypt_id_tag %}" class="btn btn-primary btn-sm" >  <i class="fas fa-trash"></i> </a> -->
															 <a href="{% url 'purchase_request:detallupurchaserequest' dados.id|encrypt_id_tag %}" class="btn btn-primary btn-sm" >  <i class="fas fa-edit"></i> Detallu Item </a>
                                                        
                                                             

                                                            </td>
														</tr>
                                                        {% endfor %}
													
													</tbody>
												</table>
											</div>
										</div>
									</div>
								</div>
								<!-- ============================================================== -->
								<!-- end recent orders  -->
	
		
								<!-- ============================================================== -->
								<!-- ============================================================== -->
								<!-- customer acquistion  -->
								<!-- ============================================================== -->
							
								<!-- ============================================================== -->
								<!-- end customer acquistion  -->
								<!-- ============================================================== -->
							</div>
				
						
						</div>

{% endblock content %}

templates/purchase_request/request_additempurchaserequest.html
{% extends 'utilizador/layout.html' %}
{% block content %}

{% load crispy_forms_tags %}



		<!-- ============================================================== -->
						<!-- pageheader  -->
						<!-- ============================================================== -->
						<div class="row">
							<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
								<div class="page-header">
									<h2 class="pageheader-title">Post Vaga </h2>
									<p class="pageheader-text">Nulla euismod urna eros, sit amet scelerisque torton lectus vel mauris facilisis faucibus at enim quis massa lobortis rutrum.</p>
									<div class="page-breadcrumb">
										<nav aria-label="breadcrumb">
											<ol class="breadcrumb">
												<li class="breadcrumb-item"><a href="#" class="breadcrumb-link">CVTL</a></li>
												<li class="breadcrumb-item active" aria-current="page">Hris Painel</li>
											</ol>

                                            
										</nav>
									</div>
								</div>
							</div>
						</div>
						<!-- ============================================================== -->
						<!-- end pageheader  -->
						<!-- ============================================================== -->
						<div class="ecommerce-widget">
	
				
                            <div class="row">
                                <div class="  col-lg-12 col-md-12 col-sm-12 col-12">
                                    <div class="card">
                                        <div class="card-header p-4">
                                             <a class="pt-2 d-inline-block" href="index.html">Kompleta Formulariu</a>
                                           
                                            <div class="float-right"> <h3 class="mb-0">Invoice #1</h3>
                                            Date: 3 Dec, 2020</div>
                                        </div>
                                        <div class="card-body">
                                       
                            {% crispy form %}
                                        </div>
                                        <div class="card-footer bg-white">
                                            <p class="mb-0">2983 Glenview Drive Corpus Christi, TX 78476</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
						
						</div>



{% endblock content %}

templates/purchase_request/request_purchaserequest.html
{% extends 'utilizador/layout.html' %}
{% block content %}

{% load crispy_forms_tags %}



		<!-- ============================================================== -->
						<!-- pageheader  -->
						<!-- ============================================================== -->
						<div class="row">
							<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
								<div class="page-header">
									<h2 class="pageheader-title">Post Vaga </h2>
									<p class="pageheader-text">Nulla euismod urna eros, sit amet scelerisque torton lectus vel mauris facilisis faucibus at enim quis massa lobortis rutrum.</p>
									<div class="page-breadcrumb">
										<nav aria-label="breadcrumb">
											<ol class="breadcrumb">
												<li class="breadcrumb-item"><a href="#" class="breadcrumb-link">CVTL</a></li>
												<li class="breadcrumb-item active" aria-current="page">Hris Painel</li>
											</ol>

                                            
										</nav>
									</div>
								</div>
							</div>
						</div>
						<!-- ============================================================== -->
						<!-- end pageheader  -->
						<!-- ============================================================== -->
						<div class="ecommerce-widget">
	
				
                            <div class="row">
                                <div class="  col-lg-12 col-md-12 col-sm-12 col-12">
                                    <div class="card">
                                        <div class="card-header p-4">
                                             <a class="pt-2 d-inline-block" href="index.html">Kompleta Formulariu</a>
                                           
                                            <div class="float-right"> <h3 class="mb-0">Invoice #1</h3>
                                            Date: 3 Dec, 2020</div>
                                        </div>
                                        <div class="card-body">
                                       
                            {% crispy form %}
                                        </div>
                                        <div class="card-footer bg-white">
                                            <p class="mb-0">2983 Glenview Drive Corpus Christi, TX 78476</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
						
						</div>



{% endblock content %}