urls.py
from django.urls import path 

from  purchase_request import views

app_name = "purchase_request"





urlpatterns = [
	path('lista/purchase/request', views.listapurchaserequest, name='listapurchaserequest'),
	path('request/purchase', views.requestpurchase, name='requestpurchase'),
	path('edit/request/purchase/<str:id>/', views.editrequestpurchase, name='editrequestpurchase'),
	path('detallu/purchase/request/<str:id>/', views.detallupurchaserequest, name='detallupurchaserequest'),
	path('add/item/purchase/<str:id_riquest>/', views.additempurchase, name='additempurchase'),

	path('edit/item/purchase/<str:id_item>/', views.edititempurchase, name='edititempurchase'),
	path('apaga/item/purchase/<str:id_item>/', views.apagaitempurchase, name='apagaitempurchase'),
	path('aproved/item/purchase/<str:id_item>/', views.aproveditempurchase, name='aproveditempurchase'),
	path('riject/item/purchase/<str:id_item>/', views.rijectitempurchase, name='rijectitempurchase'),
	path('deliver/item/purchase/<str:id_item>/', views.deliveritempurchase, name='deliveritempurchase'),
	path('send/purchase/request/<str:id>/', views.sendpurchaserequest, name='sendpurchaserequest'),


	path('acepted/purchase/request/<str:id>/', views.aceptedpurchaserequest, name='aceptedpurchaserequest'),
	path('rijected/purchase/request<str:id>/', views.rijectedpurchaserequest, name='rijectedpurchaserequest'),

															 
																 
		

]

templates/timeline.html
<center><h4 class="card-header">Timeline </h4></center>
{% load fegt9_mpg_proteksaun_url %}
<section class="cd-timeline js-cd-timeline">
	<div class="cd-timeline__container">


        <div class="cd-timeline__block js-cd-block">
			<div class="cd-timeline__img cd-timeline__img--picture js-cd-img">
				<img src="/media/icon/aseita.png" alt="Picture"> 
			</div>
			<div class="cd-timeline__content js-cd-content">
				<b>Prepara husi</b> : {{purchaserequest.employee.first_name}} {{purchaserequest.employee.last_name}} 
				{{purchaserequest.title}}<br>
				{{purchaserequest.created_at}}
			</div>
			<!-- cd-timeline__content -->
		</div>

        


        {% for dados in timeline %}
		<div class="cd-timeline__block js-cd-block">
			<div class="cd-timeline__img cd-timeline__img--picture js-cd-img">
	
{% if dados.status == "Acepted" %}   <img src="/media/icon/aseita.png" alt="Picture">  {% elif dados.status == "Review"  %} <img src="/media/icon/review.png" alt="Picture">  {% elif  dados.status == "Rejected" %}  <img src="/media/icon/rejeita.png" alt="Picture">     {% endif %}
           
          

        	

   
     
       
          
			</div>
			<!-- cd-timeline__img -->
			<div class="cd-timeline__content js-cd-content">
		
                

                  {% if forloop.last %}
                <b> Aprovasaun ikus ha sr/sra </b>   
                  {% endif %}
                    
                      {{dados.employeeuser.employee.first_name}} {{dados.employeeuser.employee.last_name}} | 	  {{dados.status}} <br>
                      <font color="black"> Pedidu  hato iha data : {{dados.created_at}} </font>'
        
            {% if dados.employeeuser.user == request.user %}
                {% if forloop.first %}
                <br>
      <span class="cd-timeline__date ">  
                        <a href="{% url 'purchase_request:aceptedpurchaserequest' dados.id|encrypt_id_tag %}" id="acceptedButton" class="btn btn-primary btn-sm">Acepted</a>
                        <a href="{% url 'purchase_request:rijectedpurchaserequest' dados.id|encrypt_id_tag %}" class="btn btn-primary btn-sm">Rejected</a> 
              </span>
                {% else %}
                        {% if dados.id|encrypt_id_tag|cekaprovasaunrequesuluk == "Acepted" %}
<br>
                    <span class="cd-timeline__date ">  
                            <a href="{% url 'purchase_request:aceptedpurchaserequest' dados.id|encrypt_id_tag %}" id="acceptedButton" class="btn btn-primary btn-sm">Acepted</a>
                            <a href="{% url 'purchase_request:rijectedpurchaserequest' dados.id|encrypt_id_tag %}" class="btn btn-primary btn-sm">Rejected</a>
                      </span>
                        {% endif %}
               {% endif %}

            {% endif %}
        
          	

               {% comment %} <span class="cd-timeline__date ">  
               <font color="black"> Pedidu  hato iha data : {{dados.created_at}} </font>'
               </span> {% endcomment %}
                
			</div>
			<!-- cd-timeline__content -->
	    	</div>

        {% endfor %}


        

		<!-- cd-timeline__block -->
	</div>
</section>